### ISSUE TITLE
Improve the test suite

### ISSUE THREAD

**Issue by funkybob** [funkybob/stencil#9]

**Comment by steenzout** [comment]
@funkybob can I help with this?

I typically use tox, pytest and travis-ci.

**Comment by funkybob** [comment]
Absolutely!

I'm generally a fan of Travis, as I know how to configure for it.

As you can see, the existing test suite is just something I cobbled together specifically for this project.

If you can translate it to a set of unittest classes, that'd be a great first step.

**Comment by steenzout** [comment]
I'll work on that tonight and ask you to review it.

**Comment by funkybob** [comment]
Fixed in #12
